kind: pipeline
type: docker
name: build

steps:
  - name: hadolint
    image: hadolint/hadolint:latest-debian
    commands:
      - hadolint --version
      - hadolint --verbose --failure-threshold warning Dockerfile

  - name: gosec
    image: securego/gosec
    commands:
      - gosec ./...

  - name: go_test
    image: golang:1.23
    commands:
      - go test -v ./...

  - name: submodules # https://docs.drone.io/pipeline/docker/syntax/cloning/
    image: alpine/git
    commands:
      - git submodule update --init --recursive

  - name: kaniko
    image: plugins/kaniko
    settings:
      username:
        from_secret: DOCKERHUB_REGISTRY_USERNAME
      password:
        from_secret: DOCKERHUB_REGISTRY_PASSWORD
      repo: pproj/tutter
      tags:
        - latest
        - ${DRONE_BUILD_NUMBER}
    when:
      branch:
        - master

  - name: telegram
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: CI_ERROR_REPORT_TELEGRAM_TOKEN
      to:
        from_secret: CI_ERROR_REPORT_TELEGRAM_CHAT_ID
    when:
      status: [ failure ]