# CI config for shell runner

stages:
  - build
  - test
  - release

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_FORCE_HTTPS: "true"

build:
  stage: build
  script:
    - make

vet:
  stage: test
  needs: []
  script:
    - go fmt ./...
    - go vet ./...

test:
  stage: test
  needs: []
  script:
    - go test -race ./...

podman:
  stage: release
  script:
    - podman build -t pproj/tutter .
    - podman push pproj/tutter
  only:
    - master
