# CI config for shell runner

stages:
  - build
  - test
  - release

build:
  stage: build
  script:
    - make

vet:
  stage: test
  needs: []
  script:
    - go fmt ./...
    - go vet ./...

test:
  stage: test
  needs: []
  script:
    - go test -race ./...

podman:
  stage: release
  script:
    - podman login --authfile $PODMAN_AUTH_FILE
    - rm -rf frontend
    - git clone git@git.sch.bme.hu:pp23/tutter-frontend.git frontend
    - podman build -t pproj/tutter .
    - podman push pproj/tutter
  only:
    - master
